create database ecomorg_db;
use ecomorg_db;

CREATE TABLE ADMINS ( adminId INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT, email VARCHAR(50) NOT NULL,
  password VARCHAR(50) NOT NULL, fullName VARCHAR(255) NOT NULL,loginType INTEGER DEFAULT 1,
  addedOn DATETIME DEFAULT CURRENT_TIMESTAMP );
  
  
SHOW TABLES;